### ISSUE TITLE
During run-time, error on receiving message.

### ISSUE THREAD

**Issue by Lamphobic** [Lamphobic/discord-robot9000#6]
See 9e8b28d8eb8a15be6f2351afc00fa88821582c99

Compiles fine (other than the reflection warnings, which I assume we're ignoring). After running, when you send a message to the bot, it errors with the following:

> Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "USERID" not found; SQL statement:

**Comment by MatthewMerrill** [comment]
Error says missing the "USERID" column... problem is probably from a Query with a String literal somewhere that column name is hardcoded.

**Comment by MatthewMerrill** [comment]
BlacklistService uses userId...

https://github.com/Lamphobic/discord-robot9000/blob/10a21aca650d7d0b1409893c44230641c351819a/src/main/java/com/mattmerr/dr9k/service/BlacklistService.java#L41

BlacklistEntry entity defines authorId instead.

https://github.com/Lamphobic/discord-robot9000/blob/10a21aca650d7d0b1409893c44230641c351819a/src/main/java/com/mattmerr/dr9k/model/BlacklistEntry.java#L33

Oops! Best fix is to change the service to authorId probably.

**Comment by Lamphobic** [comment]
Thanks. Fam.
